consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    EVENT_PREFIX: $EVENT_PREFIX
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
  annotations:
    require-adobe-auth: true
    final: true
created:
  function: created/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    __OW_NAMESPACE: $__OW_NAMESPACE
    __OW_API_KEY: $__OW_API_KEY
  annotations:
    require-adobe-auth: true
    final: true
updated:
  function: updated/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    COMMERCE_BASE_URL: $COMMERCE_BASE_URL
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
    OAUTH_SCOPES: $OAUTH_SCOPES
    ENCRYPTION_KEY: $ENCRYPTION_KEY
    ENCRYPTION_IV: $ENCRYPTION_IV
    __OW_NAMESPACE: $__OW_NAMESPACE
    __OW_API_KEY: $__OW_API_KEY
  annotations:
    require-adobe-auth: true
    final: true
deleted:
  function: deleted/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    ENCRYPTION_KEY: $ENCRYPTION_KEY
    ENCRYPTION_IV: $ENCRYPTION_IV
  annotations:
    require-adobe-auth: true
    final: true
full-sync:
  function: full-sync/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    COMMERCE_GRAPHQL_ENDPOINT: $COMMERCE_GRAPHQL_ENDPOINT
  annotations:
    require-adobe-auth: true
    final: true
